var questions = [
    "Is there anyone who\'s changed your life and doesn't know it?",
    "What do you think my strength(s) is (are)?",
    "When was the last time you surprised yourself?",
    "WILDCARD: Create your own question.",
    "What is one thing you think I can do that would dramatically improve my life?",
    "Do you think the image you have of yourself matches the image people see you as?",
    "How would you describe me to a stranger?",
    "What would make you feel closer to me?",
    "What about me intrigues you?",
    "What are you the most ashamed of?",
    "Do you think your parents did a good job raising you while you were growing up? Why or why not?",
    "Which parent are you closer to and why?",
    "Is war ever just?",
    "WILDCARD: Ask and answer the next question in a different accent.",
    "What is something you're sure you'll never experience?",
    "Do you think time is a construct of man or a rule of nature?",
    "At what point is a technologically advanced human no longer a person?",
    "Would you rather be rich and lonely or financially destitute with lots of great family and friends? Why?",
    "What is a relationship deal breaker for you?",
    "How do our personalities compliment each other?",
      "Will I find your Ex on your social media? Why or why not?",
    "Would you sacrifice yourself for a stranger?",
    "If you had to get a tattoo right now, what would it be?",
    "When is it acceptable, if ever, to break the law?",
    "What is more important to you: what you say or how you say it?",
    "If you had the option to know your date of death, would you want to?",
    "What is more important: intelligence, or wisdom?",
    "What's your least favorite household chore?",
    "What's your favorite breakfast cereal?",
    "Ketchup on eggs?",
    "What bridges are you happy that you burned?",
    "What about me intrigues you?",
    "What compliment do you think I hear the most?",
    "If you could change gender for a day, would you? How would you spend the day?",
    "If you were elected President tomorrow, what's the first thing you'd do?",
    "Can drugs be used therapuetically? Why or why not?",
    "Would you relocate for love?",
      "Do you think I fall in love easily why or why not",
    "Do you like to cuddle?",
    "Would you rather lose an arm or a leg?",
    "What fast food restaurant do you think I'm most likely to drive through? What's my order?",
      "Finish the sentence: Just by looking at you I'd think _____________.",
      "Do I remind you of anyone you know?",
      "What subject do you think I thrived at in school and did I fail any?",
    "Would you need to sleep with someone before you considered marrying them?",
    "If you could live anywhere in the world where would it be?",
    "Where do you usually get your news?",
    "Your significant other's ex is coming into town and he/she wants to go out to dinner with them alone. How do you react?",
    "Would you consider having an open relationship, where you can see other people?",
    "What does my Instagram tell you about me?",
    "Is it a requirement that you communicate with your significant other daily, in some way (phone, email, in person, etc.)?",
    "What is your biggest irrational fear?",
    "Should there be people with obscene wealth (billionaires, trillionaires, etc).",
    "Parlez-vous français?",
    "How do you define beauty?",
    "Would you consider dating someone who generally does not eat vegetables?",
    "Is there any genre of music that you completely refuse to listen to?",
    "Flight or invisibility?",
    "A first date has gone relatively well so far. You discover that your date has absolutely no awareness of any significant current affairs from the last month. How might this make you feel?",
    "Would you prefer to have one true love forever, or lots of fun and meaningful relationships?",
    "Is making fun of someone for being thin any different from making fun of someone for being fat?",
    "Upon leaving a store, you realize you were not charged for an expensive item. What would you do?",
    "How many books do you own?",
    "Do you think that western medicine is better than alternative medicine (such as chiropractic, massage, naturopathy, herbology)?",
    "Does it bother you when people sing the wrong words to a popular song?",
    "How frequently do you bathe or shower?",
    "When you hear the name Dylan what is the first to come to mind?",
    "When you hear the name Betty what is the first to come to mind?",
    "Legal prostitution?",
    "Are you more concerned about possibility of being killed as a result of a terrorist attack or a traffic accident?",
    "While shopping at a superstore (e.g. Wal-Mart, Target, etc.), if you change your mind about buying something you've picked up, do you walk back to where you found it to put it back?",
    "How would you describe what you think my type is in three words?",
    "Do you believe morality is universal, or relative?",
    "Should sex education be given to children under 15?",
    "Eliminate one carb: rice, bread, noodles, potatoes.",
    "Eliminate one condiment: ketchup, mustard, mayo, hot sauce.",
    "Eliminate one meat: poultry, beef, pork, fish.",
    "Do you prefer decadent sweets, or fruity treats?",
    "If a police officer is found guilty of a crime, do you believe the punishment should be more or less severe than for the average citizen?",
    "What is your position on hunting?",
    "Thoughts on psychadelic drugs?",
    "If you were out to dinner and your date was a vegetarian would you still order meat?",
    "How much does the sound of a person's voice affect their attractiveness to you?",
    "Does someone who refuses to take care of their body (e.g. diet, cleanliness, etc.) have the right to complain about not getting laid?",
    "Do you make your bed most days?",
    "Have you ever purposely pretended to be ignorant about something you have knowledge of because you wanted to hear someone else explain it?",
    "If given the chance to vote on a law supporting assisted suicide, how would you cast your vote?",
    "Will you teach your children to believe in Santa?",
    "Would it bother you if a platonic friend touched you casually during a conversation?",
    "Does the idea of living underwater fascinate you?",
    "It's 2 AM. While driving home, you stop at an intersection with a red traffic light. After waiting over six minutes, it still hasn't changed to green. No one seems to be around. What do you do?",
    "Sky-diving or bunjee jumping?",
    "Would you consider dating someone twenty years older than you if they were really interesting and looked really good?",
    "Would you walk up to a stranger and tell them you think they're beautiful?",
    "Do you believe in an energy field that surrounds us that we can manipulate through reiki, acupuncture, chakra balancing, yoga, or some other system?",
    "Is intoxication ever an acceptable excuse for acting stupid?",
    "If you were offered the opportunity to eat human meat prepared any way you like, would you at least try it?",
    "Other things being equal, would you be more attracted to an artist or a scientist?",
    "Do you like to be the center of attention?",
    "Could you ever kill someone?",
    "Do you own any sexy underwear?",
    "A friend has become homeless. Would you let them stay with you until they are back on their feet?",
    "Would you consider having a serious relationship with an active porn star?",
    "How do you feel about GMO's?",
    "Would you allow your partner to kiss you after performing oral sex on you?",
    "Do you think that wealthy nations have a responsibility to assist developing nations?",
    "You and a friend take out a board game, and you realize that the pieces are missing. How do you feel about substituting with things like small cookies, toys, coins, etc.?",
    "Which is the smallest amount of money you would stop to pick up if you saw it laying in the street?",
    "Would you rather play Scrabble, go out dancing, or get drunk?",
    "If it were federally legalized, would you smoke mairjuana?",
    "Do you ever spit on the ground, in public?",
    "You are unloading the dishwasher. You remove an item that seems entirely clean, except for one long hair caked to the surface of it. What do you do?",
    "Would it ever be okay to break up with someone by email or text?",
    "If you knew with certainty that you could go to a wonderful afterlife and everything would be fantastic, would you kill yourself?",
    "What reality show do you think I'm most likely to binge watch? Explain.",
    "Do you consider yourself sexually open minded?",
    "Imagine you are in a serious long-term relationship and have decided it is best to break it off. Just before you can tell your partner, he or she gives you the following news: 'I have been diagnosed with cancer and probably only have one year to live.'",
    "When was the last time you surprised yourself?",
    "Can people of color be racist?",
    "Astronomy or astrology?",
    "Which of these is likely to make you more nervous: a job interview or a first date?",
      "Do you think the image you have of yourself matches the image other people see you as?",
    "Would you prefer good things happened, or interesting ones?",
      "Finish the sentence: Dating is ____________ (both players)",
      "WILDCARD: Write down the three most important things to you in a relationship (30 sec) Compare.",
      "What are you not currently giving enough time to?",
      "What do you think our most important similarities are?",
      "What do you think is one thing I could do that would drastically improve my life?",
      "What can I help you with?",
    "If you were to die, would whoever goes through your personal belongings be shocked by what they find?",
    "When a woman chooses to abort a pregnancy, should she be required to inform the father?",
    "Should evolution and creationism be taught side-by-side in public schools?",
    "Favorite color?",
    "How would you feel if your partner asked you to get tested for STDs before having sex with you for the first time?",
    "What is the most appropriate penalty for rape?",
    "Which is more offensive: book burning or flag burning?",
    "If you inadvertently found a phone number in a partner's pocket, which would you do?",
    "If you were given a choice to choose your manner of death, how would you die?",
    "Tell me a really, really stupid joke that made you laugh.",
    "If you could do one thing without suffering the consequences, what would you do?",
    "Have you always had the same political beliefs? Is there something that impacted them?",
    "Is home for you a place or a feeling? Describe that place or describe that feeling.",
    "Do you have any recurring dreams or nightmares?",
    "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
    "Out of the negative emotions of greed, anger, jealousy and hate, which one would you say affects you the most?",
    "Do you believe in extraterrestrial life? Elaborate on why or why not.",
    "Out of the positive emotions of compassion, positivity, enthusiasm and initiative, which one is your biggest strength?",
    "What would be your thought process if you were presented with irrefutable evidence that a god didn’t exist? What would be your thought process if you were presented with irrefutable evidence that a god did exist?",
    "Share your most played song at the moment.",
    " Has another’s pain ever given you joy? Be totally honest.",
    "What, if anything, is too serious to be joked about?",
    " Of all the people in your family, whose death would you find most disturbing? Why?",
    "If you were forced to pick one religion on this planet, which one would it be and why?",
    "What do you think was there before the universe came into creation?",
    "Do I intimidate you? Why or why not?",
    "Do you believe in other dimensions and parallel universes?",
    "What do you think happens after death, if anything?",
      "WILDCARD: Draw your favorite memory with me. Compare.",
    "Presented with the opportunity to be immortal would you take it?",
    "How are you really?",
    "What are you currently working through that others don\'t see?",
    "What is your most toxic trait you can admit to?",
    "What are your thoughts on having a family?",
    "What\'syour favorite song lyric that comes to your mind from the top of your head?",
    "What title would you give this chapter in your life?",
    "When was the last time you felt most yourself?",
    "What\'s a feeling you're uncomfortable sharing with me?",
    "What about me is the hardest for you to understand?",
    "What\’s something you’re glad you’ll never have to do again?",
    "Is there anything you consider absolutely unforgivable?",
    "What\’s one thing you’re scared to ask me, but really want to know the answer to?",
    "What’s your favorite way to receive affection?",
    "What do you most look forward to about getting old?",
    "When was the last time you cried and why?",
      "Have you changed your mind about anything recently?",
      "Admit something.",
      "What/s the most attractive quality about me that isn't physical?",
      "What do you think my defining characteristic is?",
      "What do you think I should know about myself that perhaps Imunaware of?",
    ]
    function newquestion() {
        var randomNumber = Math.floor(Math.random()* (questions.length));
        document.getElementById("questiondisplay").innerHTML = questions[randomNumber];
    }